'use client';

import { useLayoutEffect, useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { MessageCircle, CalendarDays, Camera, WandSparkles, Images } from 'lucide-react';

gsap.registerPlugin(ScrollTrigger);
const steps=[['Échange','On discute de votre projet, de vos envies et de ce qui rend votre histoire singulière.',MessageCircle],['Planification','Je prépare le lieu, la lumière, le rythme et chaque détail utile à la séance.',CalendarDays],['Shooting','Le jour J, je guide juste ce qu’il faut et laisse vivre tout le reste.',Camera],['Retouche','Je sélectionne et sublime chaque image avec une colorimétrie précise.',WandSparkles],['Livraison','Votre galerie privée est prête à être regardée, partagée et transmise.',Images]] as const;
export default function ProcessSteps(){const root=useRef<HTMLElement>(null),track=useRef<HTMLDivElement>(null),bar=useRef<HTMLDivElement>(null);useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add('(min-width: 900px)',()=>{if(!root.current||!track.current)return;const t=gsap.to(track.current,{x:()=>-(track.current!.scrollWidth-innerWidth),ease:'none',scrollTrigger:{trigger:root.current,start:'top top',end:()=>`+=${track.current!.scrollWidth-innerWidth}`,pin:true,scrub:1,invalidateOnRefresh:true,onUpdate:s=>gsap.set(bar.current,{scaleX:s.progress})}});return()=>t.kill()});return()=>mm.revert()},[]);return <section ref={root} className="relative overflow-hidden bg-[#060606] md:h-screen md:min-h-[700px]"><div ref={track} className="flex flex-col md:h-full md:w-max md:flex-row"><div className="flex min-h-[60vh] items-center p-8 md:h-full md:w-[55vw] md:p-[8vw]"><div><p className="eyebrow mb-7">Le processus</p><h2 className="font-serif text-[clamp(3.5rem,7vw,8rem)] leading-[.85]">De l'intention<br/>à l'image.</h2><p className="mt-8 max-w-sm text-sm leading-7 text-white/45">Un cadre clair, une place laissée à l'imprévu, et la même exigence à chaque étape.</p></div></div>{steps.map(([title,text,Icon],i)=><article key={title} className="relative flex min-h-[65vh] flex-col justify-center border-t border-white/10 p-8 md:h-full md:min-h-0 md:w-[42vw] md:border-l md:border-t-0 md:p-[6vw]"><span className="pointer-events-none absolute right-4 top-4 font-serif text-[clamp(7rem,15vw,15rem)] leading-none text-transparent [-webkit-text-stroke:1px_rgba(243,240,232,.08)]">0{i+1}</span><Icon size={34} strokeWidth={1} className="mb-10 text-[#c9a96e]"/><h3 className="font-serif text-5xl md:text-7xl">{title}</h3><p className="mt-6 max-w-sm text-sm font-light leading-7 text-white/45">{text}</p><span className="mt-10 h-px w-16 bg-[#c9a96e]"/></article>)}</div><div className="absolute bottom-0 left-0 right-0 hidden h-[3px] bg-white/5 md:block"><div ref={bar} className="h-full origin-left scale-x-0 bg-[#c9a96e]"/></div></section>}
