'use client';

import { AnimatePresence, motion, useMotionValue, useSpring, useTransform } from 'framer-motion';
import Image from 'next/image';
import { ArrowRight, Check, X } from 'lucide-react';
import { useState, type MouseEvent } from 'react';
import type { Service } from '@/data/services';
import MagneticButton from '@/components/ui/MagneticButton';

export default function ServiceCard3D({service,index}:{service:Service;index:number}){
  const [open,setOpen]=useState(false);const mx=useMotionValue(.5),my=useMotionValue(.5);const rx=useSpring(useTransform(my,[0,1],[7,-7]),{stiffness:180,damping:22});const ry=useSpring(useTransform(mx,[0,1],[-7,7]),{stiffness:180,damping:22});
  const move=(e:MouseEvent)=>{const r=e.currentTarget.getBoundingClientRect();mx.set((e.clientX-r.left)/r.width);my.set((e.clientY-r.top)/r.height)};
  return <><motion.article id={service.slug} layoutId={`service-${service.slug}`} style={{rotateX:rx,rotateY:ry,transformStyle:'preserve-3d'}} onMouseMove={move} onMouseLeave={()=>{mx.set(.5);my.set(.5)}} className="group relative min-h-[610px] overflow-hidden border border-white/10 bg-[#101010] [perspective:1200px]"><Image src={service.image} alt={service.title} fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover opacity-65 transition-all duration-1000 group-hover:scale-105 group-hover:opacity-80"/><motion.div className="pointer-events-none absolute inset-0 opacity-0 transition-opacity duration-500 group-hover:opacity-100" style={{background:useTransform([mx,my],([x,y])=>`radial-gradient(circle at ${(x as number)*100}% ${(y as number)*100}%, rgba(201,169,110,.25), transparent 38%)`)}}/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/25 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-7 md:p-10" style={{transform:'translateZ(35px)'}}><div className="mb-6 flex items-center justify-between"><span className="font-accent text-3xl text-[#c9a96e]">0{index+1}</span><span className="micro text-white/45">{service.price}</span></div><h2 className="font-serif text-[clamp(2.8rem,4.5vw,5.5rem)] leading-[.87] tracking-[-.05em]">{service.title}</h2><p className="mt-5 max-w-md text-sm font-light leading-6 text-white/55">{service.description}</p><button onClick={()=>setOpen(true)} className="link-line mt-7 inline-flex items-center gap-4 text-[8px] uppercase tracking-[.25em]">En savoir plus <ArrowRight size={13}/></button></div></motion.article>
  <AnimatePresence>{open&&<motion.div className="fixed inset-0 z-[110] overflow-y-auto bg-[#080808]" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.div layoutId={`service-${service.slug}`} className="grid min-h-screen md:grid-cols-2"><div className="relative min-h-[50vh] md:min-h-screen"><Image src={service.image} alt={service.title} fill sizes="(max-width:768px) 100vw, 50vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent"/></div><div className="relative flex items-center p-7 py-20 md:p-[8vw]"><button onClick={()=>setOpen(false)} aria-label="Fermer" className="absolute right-6 top-6 grid h-12 w-12 place-items-center rounded-full border border-white/15"><X/></button><div><p className="eyebrow mb-7">Prestation sur mesure</p><h2 className="font-serif text-[clamp(3.5rem,7vw,8rem)] leading-[.85]">{service.title}</h2><p className="mt-8 max-w-xl text-sm font-light leading-7 text-white/55">{service.longDescription}</p><p className="mt-8 font-accent text-2xl italic text-[#c9a96e]">{service.price}</p><ul className="my-10 space-y-4">{service.includes.map(item=><li key={item} className="flex items-center gap-4 border-b border-white/10 pb-4 text-xs tracking-wide text-white/70"><Check size={14} className="text-[#c9a96e]"/>{item}</li>)}</ul><MagneticButton href="/contact">Réserver <ArrowRight size={14}/></MagneticButton></div></div></motion.div></motion.div>}</AnimatePresence></>;
}
