'use client';

import { AnimatePresence, motion } from 'framer-motion';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { useMemo, useState } from 'react';
import { projects, type Project } from '@/data/projects';
import CategoryFilters from './CategoryFilters';
import { EASE } from '@/lib/constants';

function Tile({project,index}:{project:Project;index:number}){const aspect=['aspect-[.82]','aspect-[1.18]','aspect-[.72]','aspect-square'][index%4];return <motion.article layout initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.96}} transition={{duration:.55,delay:(index%4)*.04,ease:EASE}} className="masonry-item"><div className={`${aspect} image-zoom group relative overflow-hidden bg-[#111]`}><Link href={`/projet/${project.slug}`} data-cursor="view" className="absolute inset-0"><motion.div layoutId={`project-${project.slug}`} className="absolute inset-0"><Image src={project.cover} alt={`${project.title}, série ${project.category} par Hubert Baya`} fill sizes="(max-width:620px) 100vw, (max-width:900px) 50vw, 33vw" className="object-cover"/></motion.div><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent opacity-60 transition-opacity md:opacity-0 md:group-hover:opacity-100"/><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-5 md:translate-y-5 md:p-6 md:opacity-0 md:transition-all md:duration-500 md:group-hover:translate-y-0 md:group-hover:opacity-100"><div><p className="mb-2 text-[7px] uppercase tracking-[.2em] text-[#c9a96e]">{project.category} · {project.location}</p><h2 className="font-serif text-3xl">{project.title}</h2></div><ArrowUpRight size={18}/></div></Link></div></motion.article>}

export default function MasonryGrid(){const [active,setActive]=useState('Tout'),[limit,setLimit]=useState(12);const filtered=useMemo(()=>active==='Tout'?projects:projects.filter(project=>project.category===active),[active]);const displayed=filtered.slice(0,active==='Tout'?limit:filtered.length);const change=(category:string)=>{setActive(category);setLimit(12)};return <section className="bg-[#080808]"><CategoryFilters active={active} onChange={change}/><div className="container-luxe py-14 md:py-28"><div className="mb-12 flex items-end justify-between"><div><p className="micro text-[#c9a96e]">Collection active</p><h2 className="mt-3 font-serif text-4xl md:text-6xl">{active}</h2></div><p className="font-accent text-xl italic text-white/35 md:text-2xl">{filtered.length} séries</p></div><motion.div layout className="masonry"><AnimatePresence mode="popLayout">{displayed.map((project,index)=><Tile key={project.slug} project={project} index={index}/>)}</AnimatePresence></motion.div>{displayed.length<filtered.length&&<div className="mt-14 text-center"><button onClick={()=>setLimit(value=>value+12)} className="luxe-button">Charger plus <ArrowDown size={13}/></button></div>}</div></section>}
