'use client';

import { motion } from 'framer-motion';
import Image from 'next/image';
import { ArrowUpRight, RadioTower } from 'lucide-react';
import MagneticButton from '@/components/ui/MagneticButton';
import TextReveal from '@/components/ui/TextReveal';

export default function FinalCTA(){return <section className="relative flex min-h-screen items-center justify-center overflow-hidden bg-[#020303] px-5 py-28 text-center"><Image src="/images/editorial/hero-gold.webp" alt="Signal lumineux doré" fill sizes="100vw" className="object-cover opacity-24"/><div className="absolute inset-0 bg-[radial-gradient(circle_at_center,transparent_0%,#020303_68%)]"/><div className="future-grid absolute inset-0 opacity-20"/>
<div className="pointer-events-none absolute left-1/2 top-1/2 h-[min(82vw,850px)] w-[min(82vw,850px)] -translate-x-1/2 -translate-y-1/2 rounded-full border border-[#c9a96e]/12"><motion.div className="absolute inset-[8%] rounded-full border border-dashed border-white/10" animate={{rotate:360}} transition={{duration:42,repeat:Infinity,ease:'linear'}}><span className="absolute left-1/2 top-0 h-2 w-2 -translate-x-1/2 -translate-y-1/2 rounded-full bg-[#c9a96e] shadow-[0_0_25px_#c9a96e]"/></motion.div><motion.div className="absolute inset-[20%] rounded-full border border-[#c9a96e]/16" animate={{rotate:-360}} transition={{duration:28,repeat:Infinity,ease:'linear'}}><span className="absolute bottom-[8%] right-[8%] h-1.5 w-1.5 rounded-full bg-[#8fb6bb] shadow-[0_0_18px_#8fb6bb]"/></motion.div></div>
<div className="relative z-10 max-w-6xl"><motion.div initial={{opacity:0,scale:.8}} whileInView={{opacity:1,scale:1}} viewport={{once:true}} className="mx-auto mb-8 grid h-16 w-16 place-items-center rounded-full border border-[#c9a96e]/35 bg-black/35 backdrop-blur-md"><RadioTower size={20} className="text-[#c9a96e]"/></motion.div><p className="mb-8 text-[7px] uppercase tracking-[.44em] text-[#c9a96e]">Channel open / Ready to connect</p><h2 className="font-serif text-[clamp(3.2rem,8.5vw,9.2rem)] leading-[.8] tracking-[-.065em]"><TextReveal>CRÉONS LA PROCHAINE IMAGE.</TextReveal></h2><p className="mx-auto mt-8 max-w-xl text-sm font-light leading-7 text-white/45">Un portrait, un lieu, une histoire ou une idée encore sans forme. Initialisons la conversation.</p><div className="mt-10 flex flex-col items-center justify-center gap-6 sm:flex-row"><MagneticButton href="/contact">Ouvrir le canal <ArrowUpRight size={14}/></MagneticButton><a href="/portfolio" className="link-line text-[7px] uppercase tracking-[.27em]">Explorer 35 séries</a></div><div className="mx-auto mt-16 flex max-w-md justify-between border-t border-white/10 pt-4 text-[6px] uppercase tracking-[.24em] text-white/25"><span>Paris / France</span><span>Response / 48H</span><span>Signal / Secure</span></div></div><div className="scanline absolute inset-0"/></section>}
