'use client';

import { useLayoutEffect, useRef } from 'react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, Crosshair } from 'lucide-react';
import { services } from '@/data/services';

gsap.registerPlugin(ScrollTrigger);

export default function HorizontalServices(){const root=useRef<HTMLElement>(null),track=useRef<HTMLDivElement>(null),progress=useRef<HTMLDivElement>(null);useLayoutEffect(()=>{const mm=gsap.matchMedia();mm.add('(min-width: 900px)',()=>{if(!root.current||!track.current)return;const tween=gsap.to(track.current,{x:()=>-(track.current!.scrollWidth-window.innerWidth),ease:'none',scrollTrigger:{trigger:root.current,start:'top top',end:()=>`+=${track.current!.scrollWidth-window.innerWidth}`,scrub:1,pin:true,invalidateOnRefresh:true,onUpdate:self=>gsap.set(progress.current,{scaleX:self.progress})}});return()=>tween.kill()});return()=>mm.revert()},[]);
return <section ref={root} className="relative overflow-hidden bg-[#030404] md:h-screen md:min-h-[720px]"><div ref={track} className="flex flex-col md:h-full md:w-max md:flex-row"><div className="relative flex min-h-[68vh] items-center p-7 md:h-full md:w-[58vw] md:p-[7vw]"><div className="future-grid absolute inset-0 opacity-20"/><div className="relative"><p className="mb-7 flex items-center gap-3 text-[7px] uppercase tracking-[.4em] text-[#c9a96e]"><Crosshair size={14}/> Capabilities matrix</p><h2 className="font-serif text-[clamp(4rem,8vw,9rem)] leading-[.72] tracking-[-.065em]">SIX WAYS<br/><span className="text-transparent [-webkit-text-stroke:1px_rgba(243,240,232,.4)]">TO SEE.</span></h2><p className="mt-9 max-w-md text-xs font-light leading-6 text-white/38">Un protocole visuel adapté à chaque histoire. Faites défiler pour parcourir les champs d'intervention.</p></div></div>{services.map((service,index)=><article key={service.slug} className="relative grid min-h-screen overflow-hidden border-t border-white/10 md:h-full md:min-h-0 md:w-[82vw] md:grid-cols-[.55fr_.45fr] md:border-l md:border-t-0"><div className="relative min-h-[55vh] overflow-hidden"><Image src={service.image} alt={service.title} fill sizes="(max-width:900px) 100vw, 50vw" className="object-cover opacity-72"/><div className="absolute inset-0 bg-gradient-to-r from-transparent to-[#050606]/65"/><div className="scanline absolute inset-0"/><span className="absolute left-5 top-5 text-[7px] uppercase tracking-[.3em] text-white/45">Input / Visual field 0{index+1}</span><span className="absolute bottom-5 left-5 h-8 w-8 border-b border-l border-[#c9a96e]"/></div><div className="relative flex flex-col justify-center p-7 md:p-[5vw]"><span className="pointer-events-none absolute right-5 top-4 font-serif text-[clamp(7rem,13vw,13rem)] leading-none text-transparent [-webkit-text-stroke:1px_rgba(201,169,110,.12)]">0{index+1}</span><p className="mb-5 text-[7px] uppercase tracking-[.34em] text-[#c9a96e]">Module / {service.slug}</p><h3 className="relative font-serif text-[clamp(3rem,6.5vw,7rem)] leading-[.78] tracking-[-.06em]">{service.title}</h3><p className="mt-8 max-w-md text-sm font-light leading-7 text-white/45">{service.description}</p><div className="mt-8 grid grid-cols-2 gap-3 border-y border-white/10 py-4 text-[6px] uppercase tracking-[.22em] text-white/30"><span>Resolution / Ultra</span><span>Delivery / Private</span><span>Direction / Included</span><span>Location / Global</span></div><Link href={`/services#${service.slug}`} className="mt-8 inline-flex w-fit items-center gap-5 text-[8px] uppercase tracking-[.27em] text-white/70 transition-colors hover:text-[#c9a96e]">Initialize project <ArrowUpRight size={14}/></Link></div></article>)}</div><div className="absolute bottom-0 left-0 right-0 hidden h-[3px] bg-white/5 md:block"><div ref={progress} className="h-full origin-left scale-x-0 bg-[#c9a96e]"/></div></section>}
