'use client';

import { motion } from 'framer-motion';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowUpRight, ScanLine } from 'lucide-react';
import { projects } from '@/data/projects';
import { EASE } from '@/lib/constants';

const selection=['Portrait','Mariage','Architecture','Mode','Événementiel'].map(category=>projects.find(project=>project.category===category)!);
const layouts=['md:col-span-7 md:row-span-2 aspect-[1.28] md:aspect-auto','md:col-span-5 aspect-[1.6]','md:col-span-5 aspect-[1.6]','md:col-span-5 aspect-[1.15]','md:col-span-7 aspect-[1.7]'];

export default function PortfolioPreview(){return <section className="relative overflow-hidden bg-[#030404] py-28 md:py-44"><div className="future-grid absolute inset-0 opacity-[.12]"/><div className="container-luxe relative"><div className="mb-16 grid gap-8 border-b border-white/10 pb-10 md:grid-cols-[1fr_auto] md:items-end"><div><div className="mb-6 flex items-center gap-3"><ScanLine size={14} className="text-[#c9a96e]"/><p className="text-[7px] uppercase tracking-[.42em] text-white/38">Curated visual database</p></div><h2 className="font-serif text-[clamp(3.8rem,10vw,10rem)] leading-[.72] tracking-[-.07em]">SELECTED<br/><span className="ml-[12vw] text-transparent [-webkit-text-stroke:1px_rgba(243,240,232,.4)]">SIGNALS</span></h2></div><div className="flex items-center gap-8"><p className="text-[7px] uppercase leading-5 tracking-[.24em] text-white/28">Archive size<br/><span className="text-[#c9a96e]">035 frames</span></p><Link href="/portfolio" className="grid h-20 w-20 place-items-center rounded-full border border-[#c9a96e]/45 transition-all hover:rotate-45 hover:bg-[#c9a96e] hover:text-black" aria-label="Tout le portfolio"><ArrowUpRight/></Link></div></div>
      <div className="grid auto-rows-[minmax(220px,30vw)] grid-cols-1 gap-3 md:grid-cols-12">{selection.map((project,index)=><motion.article key={project.slug} initial={{opacity:0,y:55,clipPath:'inset(12% 0 12% 0)'}} whileInView={{opacity:1,y:0,clipPath:'inset(0% 0 0% 0)'}} viewport={{once:true,amount:.12}} transition={{duration:1,delay:(index%3)*.08,ease:EASE}} className={`${layouts[index]} group tech-frame relative min-h-[280px] overflow-hidden`}><Link href={`/projet/${project.slug}`} data-cursor="view" className="absolute inset-0"><Image src={project.cover} alt={`${project.title}, ${project.category}`} fill sizes="(max-width:768px) 100vw, 65vw" className="object-cover opacity-72 transition-all duration-1000 group-hover:scale-[1.045] group-hover:opacity-95"/><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-black/20"/><div className="scanline absolute inset-0 opacity-0 transition-opacity group-hover:opacity-40"/><div className="absolute left-4 top-4 flex items-center gap-3"><span className="text-[7px] tracking-[.25em] text-[#c9a96e]">FRAME_0{index+1}</span><span className="h-px w-8 bg-white/25"/><span className="text-[6px] uppercase tracking-[.2em] text-white/45">{project.category}</span></div><div className="absolute inset-x-0 bottom-0 flex items-end justify-between p-5 md:p-7"><div><h3 className="font-serif text-3xl md:text-5xl">{project.title}</h3><p className="mt-2 text-[6px] uppercase tracking-[.27em] text-white/40">{project.location} / {project.year}</p></div><ArrowUpRight size={18} className="text-[#c9a96e] transition-transform group-hover:-translate-y-1 group-hover:translate-x-1"/></div><span className="absolute right-4 top-4 h-5 w-5 border-r border-t border-[#c9a96e]/65"/></Link></motion.article>)}</div>
    </div></section>}
