'use client';

import { motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Quote, Radio } from 'lucide-react';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { testimonials } from '@/data/testimonials';
import { EASE } from '@/lib/constants';

export default function Testimonials3D(){const [active,setActive]=useState(0);const move=(direction:number)=>setActive(value=>(value+direction+testimonials.length)%testimonials.length);useEffect(()=>{const id=setInterval(()=>move(1),6500);return()=>clearInterval(id)},[]);return <section className="relative overflow-hidden bg-[#050606] py-28 md:py-44"><div className="future-grid absolute inset-0 opacity-10"/><div className="container-luxe relative"><div className="mb-16 grid gap-8 md:grid-cols-[1fr_auto] md:items-end"><div><p className="mb-5 flex items-center gap-3 text-[7px] uppercase tracking-[.4em] text-[#c9a96e]"><Radio size={13}/> Incoming transmissions</p><h2 className="font-serif text-[clamp(3rem,7vw,7.5rem)] leading-[.82]">CLIENT<br/><span className="ml-[8vw] text-transparent [-webkit-text-stroke:1px_rgba(243,240,232,.4)]">FREQUENCIES</span></h2></div><p className="text-right text-[7px] uppercase leading-5 tracking-[.22em] text-white/28">Encrypted feedback<br/>Signal strength / 100%</p></div>
<div className="relative mx-auto h-[430px] max-w-6xl [perspective:1400px] md:h-[500px]">{testimonials.map((testimonial,index)=>{const raw=index-active;const offset=((raw+testimonials.length+2)%testimonials.length)-2;return <motion.article key={testimonial.name} className="tech-frame absolute left-1/2 top-0 grid h-full w-[min(88vw,760px)] -translate-x-1/2 overflow-hidden md:grid-cols-[.38fr_.62fr]" animate={{x:`calc(-50% + ${offset*47}%)`,scale:offset===0?1:.79,rotateY:offset*-20,z:offset===0?70:-140,opacity:Math.abs(offset)<=1?(offset===0?1:.22):0,zIndex:10-Math.abs(offset)}} transition={{duration:.85,ease:EASE}}><div className="relative hidden md:block"><Image src={testimonial.image} alt="" fill sizes="290px" className="object-cover opacity-75 grayscale"/><div className="scanline absolute inset-0"/><span className="absolute left-4 top-4 text-[6px] tracking-[.22em] text-[#c9a96e]">ID_0{index+1}</span></div><div className="flex flex-col justify-between p-8 md:p-12"><div className="flex items-center justify-between"><Quote size={34} strokeWidth={1} className="text-[#c9a96e]"/><span className="status-dot"/></div><blockquote className="font-accent text-[clamp(1.7rem,3vw,2.8rem)] italic leading-tight text-white/88">“{testimonial.quote}”</blockquote><div className="border-t border-white/10 pt-5"><p className="text-[9px] uppercase tracking-[.24em]">{testimonial.name}</p><p className="mt-2 text-[7px] uppercase tracking-[.23em] text-[#c9a96e]">{testimonial.type}</p></div></div></motion.article>})}</div>
<div className="mt-8 flex items-center justify-center gap-5"><button onClick={()=>move(-1)} aria-label="Précédent" className="grid h-12 w-12 place-items-center border border-white/15 hover:border-[#c9a96e]"><ArrowLeft size={15}/></button><span className="text-[7px] tracking-[.28em] text-white/38">0{active+1} / 0{testimonials.length}</span><button onClick={()=>move(1)} aria-label="Suivant" className="grid h-12 w-12 place-items-center border border-white/15 hover:border-[#c9a96e]"><ArrowRight size={15}/></button></div></div></section>}
