'use client';

import { AnimatePresence, motion } from 'framer-motion';
import { ArrowRight, Check } from 'lucide-react';
import { FormEvent, useState } from 'react';

export default function ContactForm(){const [sent,setSent]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState('');const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setLoading(true);setError('');const form=new FormData(e.currentTarget);try{const response=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form.entries()))});if(!response.ok)throw new Error();setSent(true)}catch{setError("Une erreur est survenue. Vous pouvez aussi m'écrire directement par email.")}finally{setLoading(false)}};return <div>{!sent?<motion.form onSubmit={submit} initial="hidden" whileInView="visible" viewport={{once:true}} variants={{hidden:{},visible:{transition:{staggerChildren:.09}}}} className="space-y-4">{[
  {name:'name',label:'Votre nom',type:'text',required:true},
  {name:'email',label:'Votre email',type:'email',required:true},
  {name:'phone',label:'Téléphone (optionnel)',type:'tel',required:false},
].map(f=><motion.div variants={{hidden:{opacity:0,y:20},visible:{opacity:1,y:0}}} className="field" key={f.name}><input id={f.name} name={f.name} type={f.type} placeholder=" " required={f.required}/><label htmlFor={f.name}>{f.label}</label></motion.div>)}
  <motion.div variants={{hidden:{opacity:0,y:20},visible:{opacity:1,y:0}}} className="field"><select id="service" name="service" required defaultValue=""><option value="" disabled hidden></option><option>Portrait</option><option>Mariage</option><option>Architecture & immobilier</option><option>Famille</option><option>Mode & éditorial</option><option>Événementiel</option></select><label htmlFor="service">Type de prestation</label></motion.div>
  <motion.div variants={{hidden:{opacity:0,y:20},visible:{opacity:1,y:0}}} className="field"><input id="date" name="date" type="date" placeholder=" "/><label htmlFor="date">Date souhaitée</label></motion.div>
  <motion.div variants={{hidden:{opacity:0,y:20},visible:{opacity:1,y:0}}} className="field"><textarea id="message" name="message" placeholder=" " required/><label htmlFor="message">Parlez-moi de votre projet</label></motion.div>
  <motion.button variants={{hidden:{opacity:0,y:20},visible:{opacity:1,y:0}}} type="submit" disabled={loading} className="luxe-button mt-7 w-full sm:w-auto">{loading?'Envoi en cours…':<>Envoyer le message <ArrowRight size={14}/></>}</motion.button>{error&&<p role="alert" className="pt-4 text-xs text-red-300">{error}</p>}<p className="pt-3 text-[8px] leading-5 text-white/30">En envoyant ce formulaire, vous acceptez d'être recontacté au sujet de votre demande.</p>
</motion.form>:<motion.div initial={{opacity:0,scale:.92}} animate={{opacity:1,scale:1}} className="flex min-h-[520px] flex-col items-center justify-center border border-white/10 bg-white/[.02] p-8 text-center"><motion.span initial={{pathLength:0}} animate={{pathLength:1}} className="grid h-20 w-20 place-items-center rounded-full border border-[#c9a96e] text-[#c9a96e]"><Check size={30}/></motion.span><h3 className="mt-8 font-serif text-4xl">Merci.</h3><p className="mt-4 max-w-sm text-sm leading-7 text-white/50">Votre message a bien été préparé. Hubert vous répondra avec attention sous 48 heures.</p><button onClick={()=>setSent(false)} className="link-line mt-8 text-[8px] uppercase tracking-[.22em]">Envoyer un autre message</button></motion.div>}</div>}
